swagger: "2.0"
info:
  description: "API documentation for the Chat Client application."
  version: "1.0.0"
  title: "Chat Client API"
host: "localhost:8080"
basePath: "/api"
schemes:
  - "http"
paths:
  /chat/send:
    post:
      summary: "Send a chat message"
      parameters:
        - name: "message"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/ChatMessage"
      responses:
        200:
          description: "Message sent successfully"
        400:
          description: "Invalid input"
  /chat/messages:
    get:
      summary: "Get chat messages"
      responses:
        200:
          description: "A list of chat messages"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ChatMessage"
definitions:
  ChatMessage:
    type: "object"
    properties:
      sender:
        type: "string"
      content:
        type: "string"
      timestamp:
        type: "string"
        format: "date-time"